#!/command/with-contenv bash

update_config() {
    print_debug "Updating '\$${1}' with value '${2}"
    sed -i -e "s#\$${1} = .*#\$${1} = \"${2}\";#g" ${NGINX_WEBROOT}/conf/config.inc.php
}

update_config_noquote() {
    print_debug "Updating \$${1} with value '${2}"
    sed -i -e "s#${1} = .*#${1} = ${2};#g" ${NGINX_WEBROOT}/conf/config.inc.php
}

add_to_config() {
    if [[ -z "${2}" ]] ; then
        print_debug "Not adding '\$${1}', no value provided"
    else
        print_debug "Adding '\$${1}' with value '${2}"
        echo "${1} = \"${2}\"" >> ${NGINX_WEBROOT}/conf/config.inc.php
    fi
}
