#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then

	## Setting up files and paths
	mkdir -p /www/logs/
	touch /www/logs/self-service-password
	chown nginx:www-data /www/logs/self-service-password

	AD_OPT_CHANGE_EXPIRED_PASSWORD=${AD_OPT_CHANGE_EXPIRED_PASSWORD:-false}
	AD_OPT_FORCE_PWD_CHANGE=${AD_OPT_FORCE_PWD_CHANGE:-false}
	AD_OPT_FORCE_UNLOCK=${AD_OPT_FORCE_UNLOCK:-false}
	ADMODE=${ADMODE:-false}
	BACKGROUND=${BACKGROUND:-'images/unsplash-space.jpeg'}
	CHANGE_SSHKEY=${CHANGE_SSHKEY:-'false'}
	CHANGE_SSHKEY_ATTRIBUTE=${CHANGE_SSHKEY_ATTRIBUTE:-'sshPublicKey'}
	DEBUG_MODE=${DEBUG_MODE:-false}
	DEFAULT_ACTION=${DEFAULT_ACTION:-'change'}
	IS_BEHIND_PROXY=${IS_BEHIND_PROXY:-false}
	LANG=${LANG:-'en'}
	LDAP_BASE_SEARCH=${LDAP_BASE_SEARCH:-}
	LDAP_BINDDN=${LDAP_BINDDN:-}
	LDAP_BINDPASS=${LDAP_BINDPASS:-}
	LDAP_FULLNAME_ATTRIBUTE=${LDAP_FULLNAME_ATTRIBUTE:-'cn'}
	LDAP_LOGIN_ATTRIBUTE=${LDAP_LOGIN_ATTRIBUTE:-'uid'}
	LDAP_MAIL_ATTRIBUTE=${LDAP_MAIL_ATTRIBUTE:-'mail'}
	LDAP_SERVER=${LDAP_SERVER:-}
	LDAP_STARTTLS=${LDAP_STARTTLS:-false}
	LOGO=${LOGO:-'images/ltb-logo.png'}
	MAIL_FROM=${MAIL_FROM:-'admin@example.com'}
	MAIL_FROM_NAME=${MAIL_FROM_NAME:-'No Reply'}
	NOTIFY_ON_CHANGE=${NOTIFY_ON_CHANGE:-false}
	NOTIFY_ON_SSHKEY_CHANGE=${NOTIFY_ON_SSHKEY_CHANGE:-true}
	PASSWORD_HASH=${PASSWORD_HASH:-'clear'}
	PASSWORD_MAX_LENGTH=${PASSWORD_MAX_LENGTH:-0}
	PASSWORD_MIN_DIGIT=${PASSWORD_MIN_DIGIT:-0}
	PASSWORD_MIN_LENGTH=${PASSWORD_MIN_LENGTH:-0}
	PASSWORD_MIN_LOWERCASE=${PASSWORD_MIN_LOWERCASE:-0}
	PASSWORD_MIN_SPECIAL=${PASSWORD_MIN_SPECIAL:-0}
	PASSWORD_MIN_UPPERCASE=${PASSWORD_MIN_UPPERCASE:-0}
	PASSWORD_NO_REUSE=${PASSWORD_NO_REUSE:-true}
	PASSWORD_SHOW_POLICY=${PASSWORD_SHOW_POLICY:-'never'}
	PASSWORD_SHOW_POLICY_POSITION=${PASSWORD_SHOW_POLICY_POSITION:-'above'}
	PUBLIC_URL=${PUBLIC_URL:-'generated'}
	QUESTIONS_ENABLED=${QUESTIONS_ENABLED:-true}
	RECAPTCHA_PRIV_KEY=${RECAPTCHA_PRIV_KEY:-}
	RECAPTCHA_PUB_KEY=${RECAPTCHA_PUB_KEY:-}
	RECAPTCHA_SIZE=${RECAPTCHA_SIZE:-'normal'}
	RECAPTCHA_THEME=${RECAPTCHA_THEME:-'light'}
	RECAPTCHA_TYPE=${RECAPTCHA_TYPE:-'image'}
	SAMBA_MODE=${SAMBA_MODE:-false}
	SECRETEKEY=${SECRETEKEY:-'secret'}
	SHADOW_OPT_UPDATE_SHADOWEXPIRE=${SHADOW_OPT_UPDATE_SHADOWEXPIRE:-false}
	SHADOW_OPT_UPDATE_SHADOWLASTCHANGE=${SHADOW_OPT_UPDATE_SHADOWLASTCHANGE:-false}
	SHOW_HELP=${SHOW_HELP:-true}
	SMTP_AUTH_ON=${SMTP_AUTH_ON:-false}
	SMTP_AUTOTLS=${SMTP_AUTOTLS:-false}
	SMTP_DEBUG=${SMTP_DEBUG:-0}
	SMTP_HOST=${SMTP_HOST:-}
	SMTP_PASS=${SMTP_PASS:-}
	SMTP_PORT=${SMTP_PORT:-587}
	SMTP_SECURE_TYPE=${SMTP_SECURE_TYPE:-tls}
	SMTP_USER=${SMTP_USER:-}
	USE_TOKENS=${USE_TOKENS:-true}
	TOKEN_LIFETIME=${TOKEN_LIFETIME:-3600}
	USE_RECAPTCHA=${USE_RECAPTCHA:-false}
	USE_SMS=${USE_SMS:-false}
	WHO_CAN_CHANGE_PASSWORD=${WHO_CAN_CHANGE_PASSWORD:-'user'}
	WHO_CAN_CHANGE_SSHKEY=${WHO_CAN_CHANGE_SSHKEY:-'user'}
	SKIP_MAIL=${SKIP_MAIL:-'false'}

	if [[ ${IS_BEHIND_PROXY} == true  ]]; then
		if [[ "${PUBLIC_URL}" == "generated" ]]; then
			sed -i 's/#\$reset_url = /\$reset_url = /g' /assets/ssp/config.inc.php.template
		else
			sed -i -r 's/#\$reset_url = .+$/\$reset_url = "<PUBLIC_URL>";/g' /assets/ssp/config.inc.php.template
		fi
	fi

	sed -i -e "s|<LDAP_SERVER>|$LDAP_SERVER|g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_STARTTLS>/$LDAP_STARTTLS/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_BINDDN>/$LDAP_BINDDN/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_BINDPASS>/$LDAP_BINDPASS/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_BASE_SEARCH>/$LDAP_BASE_SEARCH/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_LOGIN_ATTRIBUTE>/$LDAP_LOGIN_ATTRIBUTE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_FULLNAME_ATTRIBUTE>/$LDAP_FULLNAME_ATTRIBUTE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<ADMODE>/$ADMODE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<AD_OPT_FORCE_UNLOCK>/$AD_OPT_FORCE_UNLOCK/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<AD_OPT_FORCE_PWD_CHANGE>/$AD_OPT_FORCE_PWD_CHANGE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<AD_OPT_CHANGE_EXPIRED_PASSWORD>/$AD_OPT_CHANGE_EXPIRED_PASSWORD/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SAMBA_MODE>/$SAMBA_MODE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SHADOW_OPT_UPDATE_SHADOWLASTCHANGE>/$SHADOW_OPT_UPDATE_SHADOWLASTCHANGE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SHADOW_OPT_UPDATE_SHADOWEXPIRE>/$SHADOW_OPT_UPDATE_SHADOWEXPIRE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_HASH>/$PASSWORD_HASH/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_MIN_LENGTH>/$PASSWORD_MIN_LENGTH/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_MAX_LENGTH>/$PASSWORD_MAX_LENGTH/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_MIN_LOWERCASE>/$PASSWORD_MIN_LOWERCASE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_MIN_UPPERCASE>/$PASSWORD_MIN_UPPERCASE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_MIN_DIGIT>/$PASSWORD_MIN_DIGIT/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_MIN_SPECIAL>/$PASSWORD_MIN_SPECIAL/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_NO_REUSE>/$PASSWORD_NO_REUSE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_SHOW_POLICY_POSITION>/$PASSWORD_SHOW_POLICY_POSITION/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<PASSWORD_SHOW_POLICY>/$PASSWORD_SHOW_POLICY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s#<PUBLIC_URL>#$PUBLIC_URL#g" /assets/ssp/config.inc.php.template # A valid URL contains slashes but may not contain hashes.
	sed -i -e "s/<CHANGE_SSHKEY>/$CHANGE_SSHKEY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<CHANGE_SSHKEY_ATTRIBUTE>/$CHANGE_SSHKEY_ATTRIBUTE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<NOTIFY_ON_SSHKEY_CHANGE>/$NOTIFY_ON_SSHKEY_CHANGE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<WHO_CAN_CHANGE_SSHKEY>/$WHO_CAN_CHANGE_SSHKEY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<WHO_CAN_CHANGE_PASSWORD>/$WHO_CAN_CHANGE_PASSWORD/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<QUESTIONS_ENABLED>/$QUESTIONS_ENABLED/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LDAP_MAIL_ATTRIBUTE>/$LDAP_MAIL_ATTRIBUTE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SKIP_MAIL>/$SKIP_MAIL/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<MAIL_FROM_NAME>/$MAIL_FROM_NAME/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<MAIL_FROM>/$MAIL_FROM/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<NOTIFY_ON_CHANGE>/$NOTIFY_ON_CHANGE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<USE_TOKENS>/$USE_TOKENS/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<TOKEN_LIFETIME>/$TOKEN_LIFETIME/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_DEBUG>/$SMTP_DEBUG/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_HOST>/$SMTP_HOST/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_AUTH_ON>/$SMTP_AUTH_ON/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_USER>/$SMTP_USER/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_PASS>/$SMTP_PASS/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_PORT>/$SMTP_PORT/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_SECURE_TYPE>/$SMTP_SECURE_TYPE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SMTP_AUTOTLS>/$SMTP_AUTOTLS/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<USE_SMS>/$USE_SMS/g" /assets/ssp/config.inc.php.template
	sed -i -e "s|<LOGO>|$LOGO|g" /assets/ssp/config.inc.php.template
	sed -i -e "s|<BACKGROUND>|$BACKGROUND|g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<IS_BEHIND_PROXY>/$IS_BEHIND_PROXY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SHOW_HELP>/$SHOW_HELP/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<LANG>/$LANG/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<DEBUG_MODE>/$DEBUG_MODE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<SECRETEKEY>/$SECRETEKEY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<USE_RECAPTCHA>/$USE_RECAPTCHA/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<RECAPTCHA_PUB_KEY>/$RECAPTCHA_PUB_KEY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<RECAPTCHA_PRIV_KEY>/$RECAPTCHA_PRIV_KEY/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<RECAPTCHA_THEME>/$RECAPTCHA_THEME/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<RECAPTCHA_TYPE>/$RECAPTCHA_TYPE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<RECAPTCHA_SIZE>/$RECAPTCHA_SIZE/g" /assets/ssp/config.inc.php.template
	sed -i -e "s/<DEFAULT_ACTION>/$DEFAULT_ACTION/g" /assets/ssp/config.inc.php.template

	### Check to see if this is a new install, if yes download SSP and other pieces...
	if [ ! -f /www/ssp/index.php ] ; then
	   echo "** [self-service-password] Self Service Password Not Found, Installing..."
	   mkdir -p /www/ssp/
	   tar xfz /assets/install/v${SSP_VERSION}.tar.gz --strip 1 -C /www/ssp
	   chown nginx:www-data /www/ssp
	   echo "** [self-service-password] Installation Complete"
	fi

	cp -R /assets/ssp/config.inc.php.template /www/ssp/conf/config.inc.local.php

	### Force Reset Permissions for Security
	chown -R nginx:www-data /www/ssp

	## Start nginx
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo '** [self-service-password] Starting nginx'
exec nginx
